let challenge = ' 30 Days Of JavaScript '; 
let a = /a/g
let challenge2 = 'Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon';
let challenge3 = 'You cannot end a sentence with because because because is a conjunction';
console.log(challenge);
console.log(challenge.length);
console.log(challenge.toLocaleUpperCase());
console.log(challenge.toLocaleLowerCase());
console.log(challenge.substring(3,7));
console.log(challenge.split(' '));
console.log(challenge2.split(', '));
console.log(challenge.replace('JavaScript', 'Phyton'));
console.log(challenge.charAt(15));
console.log(challenge.charCodeAt('J'));
console.log(challenge.indexOf('a'));
console.log(challenge.lastIndexOf('a'));
console.log(challenge3.indexOf('because'));
console.log(challenge3.lastIndexOf('because'));
console.log(challenge3.search('because'));
console.log(challenge.trim(' '));
console.log(challenge.startsWith(' 30'));
console.log(challenge.endsWith('Script '));
console.log(challenge.match(a));
console.log(challenge.concat('& Phyton'));
console.log(challenge.repeat(2));